#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  9 11:31:19 2017

@author: jhartmann
"""

import sys
import pymysql
import datetime
from bs4 import BeautifulSoup

try:
    import urllib.request as urllib2
except ImportError:
    import urllib2
    
pw = ''

dbuser = ''
db = ''
dbhost = ''

dbconn = pymysql.connect(host= dbhost,
                         user= dbuser,
                         passwd= pw,
                         db= db,
                         use_unicode=True,
                         charset="utf8mb4")
cursor = dbconn.cursor()


insertCommitters = 'INSERT INTO apache_committers (datasource_id, \
                                                svn_id, \
                                                real_name, \
                                                project_name, \
                                                role_on_project, \
                                                last_updated,\
                                                organization_name) \
                                                VALUES  (%s, %s, %s, %s,%s, %s, %s)'
                    
# Project Information
teamUrl = 'https://cwiki.apache.org/confluence/display/CARBONDATA/PMC+and+Committers+member+list'
project_name = 'carbonData'
role = 'Committer'
data_id = 70921

 
hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}
 
try:

    req = urllib2.Request(teamUrl,headers=hdr)
    teamHtml = urllib2.urlopen(req).read()
    soup = BeautifulSoup(teamHtml, 'html.parser')
    table = soup.find('tbody')
    rows = table.find_all('tr')
    
    #parser to get names and organizations
    j = 0
    ####Multiple Try statements to get into different levels of the loop 
    ####some text was bold, linked, or a combination
    
    
    while True:
        currentRow = rows[j]
        cells = currentRow.find_all('td')
        real_name = cells[1].contents[0]
        try:
            real_name = real_name.contents[0]
            try:
                real_name = real_name.contents[0]
                try: 
                    real_name = real_name.contents[0]
                except:
                    pass  
            except:
                pass
        except:
            pass
        screen_name = cells[2].contents[0]
        try: 
            screen_name = screen_name.contents[0]
            try: 
                screen_name = screen_name.contents[0]
            except:
                pass
        except:
            pass
        organization = cells[3].contents[0]
        try: 
            organization = organization.contents[0]
            try:
                organization = organization.contents[0]            
            except:
                pass

        except:
            pass 
        j = j + 1
        time = datetime.datetime.now()
        print((data_id, screen_name, real_name, project_name, role, time, organization))    
      
        try:     
            cursor.execute(insertCommitters, (data_id, screen_name, real_name, project_name, role, time, organization))
            dbconn.commit()
        
        except pymysql.Error as error:
               print(error)
               dbconn.rollback()        
except:
    pass

dbconn.close
