#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  8 09:59:09 2017

@author: jhartmann
"""

import sys
import pymysql
import getpass
import datetime
import re
from bs4 import BeautifulSoup

try:
    import urllib.request as urllib2
except ImportError:
    import urllib2
    
pw = ''

dbuser = ''
db = ''
dbhost = ''


dbconn = pymysql.connect(host= dbhost,
                         user= dbuser,
                         passwd= pw,
                         db= db,
                         use_unicode=True,
                         charset="utf8mb4")
cursor = dbconn.cursor()
insertCommitters = 'INSERT INTO apache_committers (datasource_id, \
                                                svn_id, \
                                                real_name, \
                                                project_name, \
                                                role_on_project, \
                                                last_updated,\
                                                organization_name) \
                                                VALUES  (%s, %s, %s, %s,%s, %s, %s)'
                    

project_name = 'accumulo'
role = 'Committer'
data_id = 70912
teamUrl = 'http://accumulo.apache.org/people/'

i = 0
    
hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}
 
try:
    #grap the team page
    req = urllib2.Request(teamUrl,headers=hdr)
    teamHtml = urllib2.urlopen(req).read()
      
    #get table information from html
    soup = BeautifulSoup(teamHtml, 'html.parser')
    div = soup.find('tbody')
    tableValues = div.find_all(['td'])
    
    #get information
    while True:
        screen_name = tableValues[i].contents
        name = screen_name[0]
        real_name = tableValues[i+1].contents
        real = real_name[0]
        time = datetime.datetime.now()
        #print(screen_name)
        
        try:
            organization = tableValues[i+2].find('a').contents 
            i = i + 4
            org_name = organization[0]
            print(org_name, " ", " ", name)
            print(data_id, name, real, project_name, role, time, org_name)
           
            #execute insert statement
            try:     
                cursor.execute(insertCommitters, (data_id, name, real, project_name, role, time, org_name))
                dbconn.commit()
                print('EXECUTED')
             
            except pymysql.Error as error:
                   print(error)
                   dbconn.rollback()
   
        except:           
            i = i + 4
            org_name = '' 
            print(org_name, " ", " ", name)
            
            #exececute insert statement
            try:
                cursor.execute(insertCommitters, (data_id, name, real, project_name, role, time, org_name))
                dbconn.commit()
            except pymysql.Error as error:
                   print(error)
                   dbconn.rollback()
except:
    pass

dbconn.close
