#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 13 10:05:51 2017

@author: jhartmann
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  7 09:01:38 2017

@author: jhartmann
"""

import sys
import pymysql
import getpass
import datetime
from bs4 import BeautifulSoup

try:
    import urllib.request as urllib2
except ImportError:
    import urllib2
    
pw = ''

dbuser = 'jhartmann'
db = 'test'
dbhost = 'flossdata.syr.edu'

dbconn = pymysql.connect(host= dbhost,
                         user= dbuser,
                         passwd= pw,
                         db= db,
                         use_unicode=True,
                         charset="utf8mb4")
cursor = dbconn.cursor()

insertProject = 'INSERT INTO apache_committers_updated ( datasource_id ,\
                                                        svn_id, \
                                                        real_name, \
                                                        project_name, \
                                                        role_on_project, \
                                                        last_updated) \
                                                        VALUES  (%s, %s, %s, %s,%s, %s)'
  
apacheCommitterListUrl = 'http://people.apache.org/committer-index.html'

hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
           'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
           'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
           'Accept-Encoding': 'none',
           'Accept-Language': 'en-US,en;q=0.8',
           'Connection': 'keep-alive'}
 
           
           
project_name = ''
role = ''
current_time = ''

           
try:
    req = urllib2.Request(apacheCommitterListUrl, headers = hdr)
    committerListHtml = urllib2.urlopen(req).read()
    
    if committerListHtml:
        role = 'Committer'
        soup = BeautifulSoup(committerListHtml, 'html.parser')
        #print(soup)
        nameTable = soup.find('table')
        #print(fullDiv)
        rows = nameTable.findChildren(['tr'])
        i = 1
        for r in rows:
           rowContents = rows[i].find_all('td')
           nameCell = rowContents[0]
           userName = nameCell.contents
           
           nameLink = nameCell.find_all('a')
           if nameLink:
               userName = nameLink[0].contents
               
           
           nameBold = nameCell.find_all('b')        
           if nameBold:
               userName = nameBold[0].contents
               
           svn_id = userName[0]          
           print(svn_id) 
        
           realNameCell = rowContents[1]
           trueName = realNameCell.contents
           
           realNameBold = realNameCell.find_all('b')           
           if realNameBold:
               trueName = realNameBold[0].contents

           realNameLink = realNameCell.find_all('a')
           if realNameLink:
               trueName = realNameLink[0].contents
               
               
      
           
           real_name = trueName[0]
           print(real_name)
           
           j = 0
           while True:
               try:

                   project = rowContents[2]
                   projectTitle = project.find_all('a')
                   project = projectTitle[j].contents
                   project_name = project[0]
                   print(project_name)
                   
                   current_time = datetime.datetime.now()
                   print(current_time)
                   print('committing')
                   cursor.execute(insertProject, ('70910', svn_id, real_name, project_name, role, current_time))                 
                   print('here')
                   dbconn.commit()
                   
                               
               except pymysql.Error as error:
                   print(error)
                   dbconn.rollback()
                  
               except: 
                   break
               j = j + 1  
           i = i + 1
           print('')
except:
    pass

        
dbconn.close()
                 
    
